### ISSUE TITLE
Opening and cloning file issue

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/html-css-your-first-lab#5]
I tried "ask a question" and in the help section i used the instructions to clear up the issue and it still didnt help. Can i please get some assistance to whether this is a software error on my part or a missing piece of some sort. Searching on google hasnt been much of a help either.
![screen shot 2016-06-27 at 2 56 12 am](https://cloud.githubusercontent.com/assets/15849032/16365788/0d0ee8a6-3c13-11e6-8235-720cffa715f6.png)

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
@IdoBok, I would first try updating your version of the IDE. The latest version is 1.8.0 -- you can download it [here](https://learn.co/ide).

Otherwise, make sure that you have entered your access token correctly. If the problem persists, let us know (preferably by opening a bug on Learn -- you can find the form to report a bug by clicking on your avatar in the upper right).
